### ISSUE TITLE
Can't get React Router to work

### ISSUE THREAD

**Issue by perborgen** [scrimba/community#93]
Try clicking the link in the preview window on this cast:

https://scrimba.com/c/cZyLQc6

**Comment by judofyr** [comment]
This is caused by two things:

- We had a bug where defaultPrevented clicks where handled as regular clicks. This has been fixed
- React Router needs to know the `basename` since we don't render from root.

I've got it working locally with this code:

```javascript
import { createBrowserHistory } from 'history';

var history = createBrowserHistory({
    basename: location.pathname
})

var routes = (
    <Router history={history}>
        <div>
            <Route exact path="/" component={App}/> 
            <Route path="/new" component={CreateApp}/>
        </div>
    </Router>
);
```

**Comment by somebee** [comment]
Does this not use the history.pushState api? If so, won't refreshing the browser fail?

**Comment by judofyr** [comment]
Well, currently we don't detect `pushState`-changes so we don't update the URL. Refreshing the browser will therefore reload the index page. It works in a sense… You could also configure React Router to use `hash` instead and everything will work as expected. I'm mainly focused on getting it to a state where you can create *some* useful React Router casts.

**Comment by dorelljames** [comment]
![FCo1N72LkA](https://user-images.githubusercontent.com/977413/61132680-74303980-a4ee-11e9-906c-c6b35b962232.gif)

Hello guys, certainly looking for a solution for React router. When entering a URL path, it doesn't seem to load the right component. Anything I missed here?

Here's the scrimba link so you guys can play around: scrimba.com/c/c8gevKsD. Thanks

**Comment by perborgen** [comment]
It works better if you use `Router` instead of `BrowserRouter` @dorelljames. Then you at least don't see the run.scrimba.com url.



However, refreshing still doesn't work as expected.

I tried with using HashRouter here @judofyr:

[https://scrimba.com/c/cnZpLQtp](https://scrimba.com/c/cnZpLQtp)

However, it displays the following error:

```text
ypeError: 'get' on proxy: property 'replace' is a read-only and non-configurable data property on the proxy target but the proxy did not return its actual value (expected 'function () { [native code] }' but got 'function () { [native code] }')
```

Any ideas?

**Comment by dorelljames** [comment]
Yeah. thanks, confirmed the behaviour you’re saying is correct @perborgen 

I’m not so particular with the error though…

**Comment by perborgen** [comment]
fixed
